services:
  web:
    build: .
    ports:
      - "5001:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    # Remove user directive to run entrypoint as root
    entrypoint: |
      bash -c '
        # Create file as root
        mkdir -p /var/www/html/public
        touch /var/www/html/public/output.txt
        chown -R www-data:www-data /var/www/html/public
        chmod 666 /var/www/html/public/output.txt
        # Switch to www-data user for Apache
        exec apache2-foreground
      '
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: SuPeL33tgoAt
      MYSQL_DATABASE: hackin
      MYSQL_USER: UbErHaxor
      MYSQL_PASSWORD: SuPeL33tgoAt
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

volumes:
  db_data: